sudo: false
dist: trusty

language: node_js
node_js:
  - 12
install:
  - npm ci

cache:
  directories:
    - "node_modules"

jobs:
  include:
    - stage: test
      script: npm test
    - stage: deploy
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        on:
          branch: master
        script: npm run release
stages:
  - test
  - deploy
