module.exports = {
    plugins: ['@typescript-eslint'],
    rules: {
        '@typescript-eslint/adjacent-overload-signatures': ['error'],
        '@typescript-eslint/array-type': ['warn', {
            default: 'array-simple',
        }],
        '@typescript-eslint/ban-ts-comment': ['error'],
        '@typescript-eslint/ban-ts-ignore': ['error'],
        '@typescript-eslint/ban-types': ['error'],
        '@typescript-eslint/brace-style': ['warn'],
        'camelcase': ['off'],
        '@typescript-eslint/camelcase': ['warn'],
        '@typescript-eslint/class-name-casing': ['error'],
        '@typescript-eslint/comma-spacing': ['warn'],
        '@typescript-eslint/consistent-type-assertions': ['error'],
        '@typescript-eslint/consistent-type-definitions': ['warn'],
        'default-param-last': ['off'],
        '@typescript-eslint/default-param-last': ['error'],
        '@typescript-eslint/explicit-function-return-type': ['off'],
        '@typescript-eslint/explicit-member-accessibility': ['off'],
        '@typescript-eslint/explicit-module-boundary-types': ['off'],
        'func-call-spacing': ['off'],
        '@typescript-eslint/func-call-spacing': ['warn'],
        '@typescript-eslint/generic-type-naming': ['off'],
        'indent': ['off'],
        '@typescript-eslint/indent': ['warn', 4, {SwitchCase: 1}],
        '@typescript-eslint/interface-name-prefix': ['off'],
        '@typescript-eslint/member-delimiter-style': ['error'],
        '@typescript-eslint/member-naming': ['off'],
        '@typescript-eslint/member-ordering': ['off'],
        '@typescript-eslint/naming-convention': ['off'],
        'no-array-constructor': ['off'],
        '@typescript-eslint/no-array-constructor': ['error'],
        'no-dupe-class-members': ['off'],
        '@typescript-eslint/no-dupe-class-members': ['error'],
        '@typescript-eslint/no-dynamic-delete': ['error'],
        'no-empty-function': ['off'],
        '@typescript-eslint/no-empty-function': ['warn'],
        '@typescript-eslint/no-empty-interface': ['warn'],
        '@typescript-eslint/no-explicit-any': ['off'],
        '@typescript-eslint/no-extra-non-null-assertion': ['off'],
        '@typescript-eslint/no-extra-parens': ['off'],
        'no-extra-semi': ['off'],
        '@typescript-eslint/no-extra-semi': ['warn'],
        '@typescript-eslint/no-extraneous-class': ['warn'],
        '@typescript-eslint/no-for-in-array': ['off'],
        '@typescript-eslint/no-inferrable-types': ['warn'],
        'no-magic-numbers': ['off'],
        '@typescript-eslint/no-magic-numbers': ['warn', {'ignore': [-1, 0, 1, 2], 'ignoreArrayIndexes': true}],
        '@typescript-eslint/no-misused-new': ['error'],
        '@typescript-eslint/no-namespace': ['error'],
        '@typescript-eslint/no-non-null-asserted-optional-chain': ['warn'],
        '@typescript-eslint/no-non-null-assertion': ['off'],
        '@typescript-eslint/no-parameter-properties': ['off'],
        '@typescript-eslint/no-require-imports': ['error'],
        '@typescript-eslint/no-this-alias': ['error'],
        '@typescript-eslint/no-type-alias': ['warn', {
            allowAliases: 'in-unions-and-intersections',
            allowCallbacks: 'always',
            allowConditionalTypes: 'always',
            allowConstructors: 'always',
            allowLiterals: 'in-unions-and-intersections',
            allowMappedTypes: 'always',
            allowTupleTypes: 'always',
        }],
        'no-unused-expressions': ['off'],
        '@typescript-eslint/no-unused-expressions': ['warn'],
        '@typescript-eslint/no-unused-vars': ['warn'],
        '@typescript-eslint/no-use-before-define': ['warn'],
        '@typescript-eslint/no-useless-constructor': ['warn'],
        '@typescript-eslint/no-var-requires': ['error'],
        '@typescript-eslint/prefer-as-const': ['warn'],
        '@typescript-eslint/prefer-for-of': ['off'],
        '@typescript-eslint/prefer-function-type': ['warn'],
        '@typescript-eslint/prefer-namespace-keyword': ['error'],
        '@typescript-eslint/prefer-optional-chain': ['warn'],
        'quotes': ['off'],
        '@typescript-eslint/quotes': ['warn', 'single'],
        '@typescript-eslint/require-array-sort-compare': ['off'],
        'semi': 'off',
        '@typescript-eslint/semi': ['warn', 'always'],
        'space-before-function-paren': ['off'],
        '@typescript-eslint/space-before-function-paren': ['warn', {anonymous: 'always', named: 'never'}],
        '@typescript-eslint/strict-boolean-expressions': ['off'],
        '@typescript-eslint/switch-exhaustiveness-check': ['off'],
        '@typescript-eslint/triple-slash-reference': ['error'],
        '@typescript-eslint/type-annotation-spacing': ['warn'],
        '@typescript-eslint/typedef': ['off'],
        '@typescript-eslint/unified-signatures': ['warn'],
    },
    overrides: [
        {
            files: ['**/*.ts?(x)'],
            rules: {
                '@typescript-eslint/await-thenable': ['error'],
                '@typescript-eslint/explicit-function-return-type': ['warn', {
                    allowExpressions: true,
                }],
                '@typescript-eslint/no-floating-promises': ['warn'],
                '@typescript-eslint/no-for-in-array': ['error'],
                '@typescript-eslint/no-implied-eval': ['error'],
                '@typescript-eslint/no-misused-promises': ['error'],
                '@typescript-eslint/no-throw-literal': ['error'],
                '@typescript-eslint/no-unnecessary-boolean-literal-compare': ['warn'],
                '@typescript-eslint/no-unnecessary-condition': ['warn'],
                '@typescript-eslint/no-unnecessary-qualifier': ['error'],
                '@typescript-eslint/no-unnecessary-type-arguments': ['warn'],
                '@typescript-eslint/no-unnecessary-type-assertion': ['warn'],
                '@typescript-eslint/no-untyped-public-signature': ['error'],
                '@typescript-eslint/no-unused-vars-experimental': ['off'],
                '@typescript-eslint/prefer-for-of': ['warn'],
                '@typescript-eslint/prefer-includes': ['warn'],
                '@typescript-eslint/prefer-nullish-coalescing': ['warn'],
                '@typescript-eslint/prefer-readonly': ['warn'],
                '@typescript-eslint/prefer-regexp-exec': ['warn'],
                '@typescript-eslint/prefer-string-starts-ends-with': ['warn'],
                '@typescript-eslint/promise-function-async': ['error'],
                '@typescript-eslint/require-await': ['error'],
                '@typescript-eslint/restrict-plus-operands': ['error', {checkCompoundAssignments: true}],
                '@typescript-eslint/restrict-template-expressions': ['error', {
                    allowBoolean: true,
                    allowNullable: true,
                    allowNumber: true,
                }],
                '@typescript-eslint/return-await': ['off'],
                '@typescript-eslint/typedef': ['warn', {
                    arrayDestructuring: false,
                    arrowParameter: false,
                    memberVariableDeclaration: true,
                    objectDestructuring: false,
                    parameter: true,
                    propertyDeclaration: true,
                    variableDeclaration: false,
                }],
                '@typescript-eslint/unbound-method': ['error', {
                    ignoreStatic: true,
                }],
            },
        },
    ],
};
